version: '3'

services:
    nginx:
        image: nginx:alpine
        volumes:
            - ./:/var/www
            - ./_docker/nginx/conf.d:/etc/nginx/conf.d
        ports:
            - "80:80"
            - "443:443"
        depends_on:
            - app
        container_name: currencies_nginx

    app:
        build:
            context: .
            dockerfile: _docker/app/Dockerfile
        volumes:
            - ./:/var/www
        depends_on:
            - db
        container_name: currencies_app

    db:
        platform: linux/x86_64
        image: mysql:8.0
        restart: always
        volumes:
            - ./tmp/db:/var/lib/mysql
            - ./_docker/mysql/mysql.cnf:/etc/mysql/my.cnf
        environment:
            MYSQL_DATABASE: Currencies
            MYSQL_ROOT_PASSWORD: qwer1234
            MYSQL_ROOT_HOST: "%"
        ports:
            - "8101:3306"
        command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
        container_name: currencies_db
